trigger: none

pool: AgentRomanoff

variables:
  working-dir : '$(System.DefaultWorkingDirectory)/env/dev/'
  
  
stages:
  - stage: CodeQuality
    displayName: SonarCube Scanner STAGE
    jobs:
      - job: SonarSCanner
        displayName: Sonar Scanner JOB  
        steps:

        - script: dir
          displayName: 'List current directory'
          
        - checkout: self
          submodules: false
          lfs: false
          fetchDepth: 1
        - task: SonarQubePrepare@7
          inputs:
            SonarQube: 'SonarQube'
            scannerMode: 'cli'
            configMode: 'manual'
            cliProjectKey: 'AvengerScan'
            cliSources: '.'
            
        - task: SonarQubeAnalyze@7
          inputs:
            jdkversion: 'JAVA_HOME_17_X64'
        - task: SonarQubePublish@7
          inputs:
            pollingTimeoutSec: '300'
        
    

        
  - stage: InitValidatePlanStage
    displayName: Init Validate Plan STAGE
    jobs: 
    - job: InitValidatePlan
      displayName: Init Validate Plan JOB
      steps:
      - task: TerraformTask@5
        displayName: Terraform Init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(working-dir)'
          commandOptions: '-reconfigure'
          backendServiceArm: 'myServiceConnection'
          backendAzureRmOverrideSubscriptionID: '224ca6aa-8178-4cd2-bcee-797840d267cf'
          backendAzureRmResourceGroupName: 'dev-hulk-rg'
          backendAzureRmStorageAccountName: 'marvelstatefile01'
          backendAzureRmContainerName: 'statefile-container'
          backendAzureRmKey: 'dev.terraform.tfstate'

      - task: TerraformTask@5
        displayName: Terraform Valiadate
        inputs:
          provider: 'azurerm'
          command: 'validate'
          workingDirectory: $(working-dir)
      
      - task: tfsec@1
        displayName: tfsec 
        inputs:
          version: 'v1.26.0'
          debug: true
          dir: '$(working-dir)'
          publishTestResults: true
      
      - task: TerraformTask@5
        displayName: Terraform Plan
        inputs:
          provider: 'azurerm'
          command: 'plan'
          workingDirectory: '$(working-dir)'
          environmentServiceNameAzureRM: 'myServiceConnection'
          
  - stage: InitAndApply 
    displayName: Init and Apply STAGE
    jobs:
    - job: InitandApply
      displayName: Init and Apply JOB
      steps:
      - task: TerraformTask@5
        displayName: Terraform Init
        inputs:
          provider: 'azurerm'
          command: 'init'
          workingDirectory: '$(working-dir)'
          commandOptions: '-reconfigure'
          backendServiceArm: 'myServiceConnection'
          backendAzureRmOverrideSubscriptionID: '224ca6aa-8178-4cd2-bcee-797840d267cf'
          backendAzureRmResourceGroupName: 'dev-hulk-rg'
          backendAzureRmStorageAccountName: 'marvelstatefile01'
          backendAzureRmContainerName: 'statefile-container'
          backendAzureRmKey: 'dev.terraform.tfstate'
    
      - task: TerraformTask@5
        displayName: Terraform Apply
        inputs:
          provider: 'azurerm'
          command: 'apply'
          workingDirectory: '$(working-dir)'
          environmentServiceNameAzureRM: 'myServiceConnection'